# Generated by Django 6.0.3 on 2026-04-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='locations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='organizations',
            field=models.TextField(blank=True),
        ),
    ]
