# Generated by Django 6.0.3 on 2026-04-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_locations_resume_organizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='min_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='required_education',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
