# Generated by Django 6.0.3 on 2026-04-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_job_min_experience_job_required_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
    ]
