# Generated by Django 6.0.3 on 2026-04-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0006_resume_education_resume_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='experience_years',
            field=models.FloatField(default=0),
        ),
    ]
